from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()
ws = wb.active
ws.title = "テスト仕様書"

# スタイル定義
header_font = Font(bold=True, size=11, color='FFFFFF')
header_fill = PatternFill('solid', start_color='4472C4')
normal_fill = PatternFill('solid', start_color='FFFFFF')
pass_fill = PatternFill('solid', start_color='C6EFCE')
fail_fill = PatternFill('solid', start_color='FFC7CE')
pending_fill = PatternFill('solid', start_color='FFEB9C')
thin_border = Border(
    left=Side(style='thin'),
    right=Side(style='thin'),
    top=Side(style='thin'),
    bottom=Side(style='thin')
)

# ヘッダー行
headers = ['テストID', 'カテゴリ', '機能', 'テスト名', 'テスト種別', '前提条件', 'テスト手順', '期待結果', '対象Phase', 'テスト結果', '実施日', '備考']
for col, header in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=header)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
    cell.border = thin_border

# テストデータ（修正済み）
test_cases = [
    # 認証テスト
    ["AUTH-001", "認証", "サインアップ", "正常なサインアップ", "正常系", "未登録ユーザー",
     "1. /api/auth/signup にPOST\n2. username: 「test_user」を入力\n3. email: 「test@example.com」を入力\n4. password: 「Password123!」を入力",
     "status: 201, accessToken/refreshToken返却", "Phase1", "", "", ""],
    ["AUTH-002", "認証", "サインアップ", "既存ユーザー名でのサインアップ", "異常系", "ユーザー名「test_user」が既に存在",
     "1. /api/auth/signup にPOST\n2. username: 「test_user」（既存）を入力\n3. email: 「new@example.com」を入力\n4. password: 「Password123!」を入力",
     "status: 409, error: USERNAME_ALREADY_EXISTS", "Phase1", "", "", ""],
    ["AUTH-003", "認証", "サインアップ", "既存メールでのサインアップ", "異常系", "メール「test@example.com」が既に存在",
     "1. /api/auth/signup にPOST\n2. username: 「new_user」を入力\n3. email: 「test@example.com」（既存）を入力\n4. password: 「Password123!」を入力",
     "status: 409, error: EMAIL_ALREADY_EXISTS", "Phase1", "", "", ""],
    ["AUTH-004", "認証", "サインアップ", "無効なメール形式", "異常系", "なし",
     "1. /api/auth/signup にPOST\n2. email: 「invalid-email」を入力（@なし）",
     "status: 400, バリデーションエラー", "Phase1", "", "", ""],
    ["AUTH-005", "認証", "サインアップ", "短いパスワード", "境界値", "なし",
     "1. /api/auth/signup にPOST\n2. password: 「Pass1!a」（7文字）を入力",
     "status: 400, パスワードは8文字以上", "Phase1", "", "", ""],
    ["AUTH-006", "認証", "サインアップ", "最小パスワード長", "境界値", "なし",
     "1. /api/auth/signup にPOST\n2. username: 「pass_test」を入力\n3. email: 「pass@example.com」を入力\n4. password: 「Pass123!」（8文字）を入力",
     "status: 201, 成功", "Phase1", "", "", ""],
    ["AUTH-007", "認証", "サインアップ", "短いユーザー名", "境界値", "なし",
     "1. /api/auth/signup にPOST\n2. username: 「ab」（2文字）を入力",
     "status: 400, ユーザー名は3文字以上", "Phase1", "", "", ""],
    ["AUTH-008", "認証", "サインアップ", "最小ユーザー名長", "境界値", "なし",
     "1. /api/auth/signup にPOST\n2. username: 「abc」（3文字）を入力\n3. email: 「abc@example.com」を入力\n4. password: 「Password123!」を入力",
     "status: 201, 成功", "Phase1", "", "", ""],
    ["AUTH-009", "認証", "サインアップ", "最大ユーザー名長", "境界値", "なし",
     "1. /api/auth/signup にPOST\n2. username: 「abcdefghij1234567890」（20文字）を入力\n3. email: 「max@example.com」を入力\n4. password: 「Password123!」を入力",
     "status: 201, 成功", "Phase1", "", "", ""],
    ["AUTH-010", "認証", "サインアップ", "ユーザー名超過", "境界値", "なし",
     "1. /api/auth/signup にPOST\n2. username: 「abcdefghij12345678901」（21文字）を入力",
     "status: 400, ユーザー名は20文字以内", "Phase1", "", "", ""],
    ["AUTH-011", "認証", "ログイン", "正常なログイン", "正常系", "登録済みユーザー（email: test@example.com）",
     "1. /api/auth/login にPOST\n2. email: 「test@example.com」を入力\n3. password: 「Password123!」を入力",
     "status: 200, accessToken/refreshToken返却", "Phase1", "", "", ""],
    ["AUTH-012", "認証", "ログイン", "無効なパスワード", "異常系", "登録済みユーザー",
     "1. /api/auth/login にPOST\n2. email: 「test@example.com」を入力\n3. password: 「WrongPass123!」（間違い）を入力",
     "status: 401, error: INVALID_CREDENTIALS", "Phase1", "", "", ""],
    ["AUTH-013", "認証", "ログイン", "存在しないメール", "異常系", "なし",
     "1. /api/auth/login にPOST\n2. email: 「notexist@example.com」を入力\n3. password: 「Password123!」を入力",
     "status: 401, error: INVALID_CREDENTIALS", "Phase1", "", "", ""],
    ["AUTH-014", "認証", "ログイン", "空のメール", "異常系", "なし",
     "1. /api/auth/login にPOST\n2. email: 「」（空文字）を入力\n3. password: 「Password123!」を入力",
     "status: 400, バリデーションエラー", "Phase1", "", "", ""],
    ["AUTH-015", "認証", "ログイン", "空のパスワード", "異常系", "なし",
     "1. /api/auth/login にPOST\n2. email: 「test@example.com」を入力\n3. password: 「」（空文字）を入力",
     "status: 400, バリデーションエラー", "Phase1", "", "", ""],
    ["AUTH-016", "認証", "トークン更新", "正常なトークン更新", "正常系", "有効なrefreshToken取得済み",
     "1. /api/auth/refresh にPOST\n2. refreshToken: 「{取得したrefreshToken}」を入力",
     "status: 200, 新accessToken返却", "Phase1", "", "", ""],
    ["AUTH-017", "認証", "トークン更新", "無効なrefreshToken", "異常系", "なし",
     "1. /api/auth/refresh にPOST\n2. refreshToken: 「invalid_token_12345」を入力",
     "status: 401, error: INVALID_TOKEN", "Phase1", "", "", ""],
    ["AUTH-018", "認証", "トークン更新", "期限切れrefreshToken", "異常系", "期限切れToken",
     "1. /api/auth/refresh にPOST\n2. refreshToken: 「{期限切れのrefreshToken}」を入力",
     "status: 401, error: TOKEN_EXPIRED", "Phase1", "", "", ""],
    ["AUTH-019", "認証", "認証情報取得", "認証済みユーザー情報取得", "正常系", "ログイン済み",
     "1. /api/auth/me にGET\n2. Authorization: 「Bearer {accessToken}」をヘッダーに設定",
     "status: 200, ユーザー情報返却", "Phase1", "", "", ""],
    ["AUTH-020", "認証", "認証情報取得", "未認証でのアクセス", "異常系", "未ログイン",
     "1. /api/auth/me にGET\n2. Authorizationヘッダーなし",
     "status: 401, error: UNAUTHORIZED", "Phase1", "", "", ""],
    ["AUTH-021", "認証", "認証情報取得", "無効なトークン", "異常系", "なし",
     "1. /api/auth/me にGET\n2. Authorization: 「Bearer invalid_token」を入力",
     "status: 401, error: INVALID_TOKEN", "Phase1", "", "", ""],
    ["AUTH-022", "認証", "ログアウト", "正常なログアウト", "正常系", "ログイン済み",
     "1. /api/auth/logout にPOST\n2. Authorization: 「Bearer {accessToken}」をヘッダーに設定",
     "status: 200, 成功メッセージ", "Phase1", "", "", ""],

    # プロフィールテスト
    ["PROF-001", "プロフィール", "取得", "自分のプロフィール取得", "正常系", "ログイン済み",
     "1. /api/profile にGET\n2. Authorization: 「Bearer {accessToken}」をヘッダーに設定",
     "status: 200, プロフィール情報返却", "Phase1", "", "", ""],
    ["PROF-002", "プロフィール", "取得", "未認証でのプロフィール取得", "異常系", "未ログイン",
     "1. /api/profile にGET\n2. Authorizationヘッダーなし",
     "status: 401", "Phase1", "", "", ""],
    ["PROF-003", "プロフィール", "更新", "表示名の更新", "正常系", "ログイン済み",
     "1. /api/profile にPUT\n2. displayName: 「新しい表示名」を入力",
     "status: 200, 更新されたプロフィール", "Phase1", "", "", ""],
    ["PROF-004", "プロフィール", "更新", "自己紹介の更新", "正常系", "ログイン済み",
     "1. /api/profile にPUT\n2. bio: 「新しい自己紹介文です。よろしくお願いします。」を入力",
     "status: 200", "Phase1", "", "", ""],
    ["PROF-005", "プロフィール", "更新", "全フィールド更新", "正常系", "ログイン済み",
     "1. /api/profile にPUT\n2. displayName: 「テストユーザー」を入力\n3. bio: 「自己紹介」を入力\n4. location: 「東京」を入力\n5. website: 「https://example.com」を入力",
     "status: 200, 全フィールド更新確認", "Phase1", "", "", ""],
    ["PROF-006", "プロフィール", "更新", "表示名の最大長", "境界値", "ログイン済み",
     "1. /api/profile にPUT\n2. displayName: 「あ」×32（32文字）を入力",
     "status: 200, 成功", "Phase1", "", "", ""],
    ["PROF-007", "プロフィール", "更新", "表示名の超過", "境界値", "ログイン済み",
     "1. /api/profile にPUT\n2. displayName: 「あ」×33（33文字）を入力",
     "status: 400, 32文字以内", "Phase1", "", "", ""],
    ["PROF-008", "プロフィール", "更新", "自己紹介の最大長", "境界値", "ログイン済み",
     "1. /api/profile にPUT\n2. bio: 「あ」×500（500文字）を入力",
     "status: 200, 成功", "Phase1", "", "", ""],
    ["PROF-009", "プロフィール", "更新", "自己紹介の超過", "境界値", "ログイン済み",
     "1. /api/profile にPUT\n2. bio: 「あ」×501（501文字）を入力",
     "status: 400, 500文字以内", "Phase1", "", "", ""],
    ["PROF-010", "プロフィール", "更新", "無効なURL形式", "異常系", "ログイン済み",
     "1. /api/profile にPUT\n2. website: 「invalid-url」を入力",
     "status: 400, URL形式エラー", "Phase1", "", "", ""],

    # 作品テスト
    ["ART-001", "作品", "一覧取得", "自分の作品一覧取得", "正常系", "ログイン済み/作品あり",
     "1. /api/artworks にGET\n2. Authorization: 「Bearer {accessToken}」をヘッダーに設定",
     "status: 200, 作品一覧返却", "Phase1", "", "", ""],
    ["ART-002", "作品", "一覧取得", "作品なしの一覧取得", "正常系", "ログイン済み/作品なし",
     "1. /api/artworks にGET",
     "status: 200, 空配列", "Phase1", "", "", ""],
    ["ART-003", "作品", "作成", "新規作品作成", "正常系", "ログイン済み",
     "1. /api/artworks にPOST\n2. title: 「テスト作品」を入力\n3. imageUrl: 「https://example.com/image.jpg」を入力\n4. description: 「作品の説明文」を入力",
     "status: 201, 作成された作品", "Phase1", "", "", ""],
    ["ART-004", "作品", "作成", "タイトルなしで作成", "異常系", "ログイン済み",
     "1. /api/artworks にPOST\n2. title: 「」（空）\n3. imageUrl: 「https://example.com/image.jpg」を入力",
     "status: 400, titleは必須", "Phase1", "", "", ""],
    ["ART-005", "作品", "作成", "画像URLなしで作成", "異常系", "ログイン済み",
     "1. /api/artworks にPOST\n2. title: 「テスト」を入力\n3. imageUrl: 「」（空）",
     "status: 400, imageUrlは必須", "Phase1", "", "", ""],
    ["ART-006", "作品", "作成", "最大タイトル長", "境界値", "ログイン済み",
     "1. /api/artworks にPOST\n2. title: 「あ」×200（200文字）を入力\n3. imageUrl: 「https://example.com/image.jpg」を入力",
     "status: 201, 成功", "Phase1", "", "", ""],
    ["ART-007", "作品", "作成", "タイトル超過", "境界値", "ログイン済み",
     "1. /api/artworks にPOST\n2. title: 「あ」×201（201文字）を入力",
     "status: 400, 200文字以内", "Phase1", "", "", ""],
    ["ART-008", "作品", "取得", "作品詳細取得", "正常系", "ログイン済み/作品あり",
     "1. /api/artworks/{id} にGET\n2. id: 「1」（作成した作品ID）を指定",
     "status: 200, 作品詳細", "Phase1", "", "", ""],
    ["ART-009", "作品", "取得", "存在しない作品取得", "異常系", "ログイン済み",
     "1. /api/artworks/{id} にGET\n2. id: 「99999」（存在しないID）を指定",
     "status: 404, NOT_FOUND", "Phase1", "", "", ""],
    ["ART-010", "作品", "取得", "他ユーザーの作品取得", "異常系", "ログイン済み",
     "1. /api/artworks/{id} にGET\n2. id: 「{他ユーザーの作品ID}」を指定",
     "status: 403, FORBIDDEN", "Phase1", "", "", ""],
    ["ART-011", "作品", "更新", "作品タイトル更新", "正常系", "ログイン済み/作品あり",
     "1. /api/artworks/{id} にPUT\n2. id: 「1」を指定\n3. title: 「更新後タイトル」を入力",
     "status: 200, 更新された作品", "Phase1", "", "", ""],
    ["ART-012", "作品", "更新", "他ユーザーの作品更新", "異常系", "ログイン済み",
     "1. /api/artworks/{id} にPUT\n2. id: 「{他ユーザーの作品ID}」を指定\n3. title: 「更新」を入力",
     "status: 403, FORBIDDEN", "Phase1", "", "", ""],
    ["ART-013", "作品", "削除", "作品削除", "正常系", "ログイン済み/作品あり",
     "1. /api/artworks/{id} にDELETE\n2. id: 「1」を指定",
     "status: 200 or 204", "Phase1", "", "", ""],
    ["ART-014", "作品", "削除", "他ユーザーの作品削除", "異常系", "ログイン済み",
     "1. /api/artworks/{id} にDELETE\n2. id: 「{他ユーザーの作品ID}」を指定",
     "status: 403, FORBIDDEN", "Phase1", "", "", ""],
    ["ART-015", "作品", "並び替え", "作品の並び替え", "正常系", "ログイン済み/複数作品",
     "1. /api/artworks/reorder にPUT\n2. orderedIds: 「[3, 1, 2]」を入力",
     "status: 200, 並び順更新", "Phase1", "", "", ""],
    ["ART-016", "作品", "プラン制限", "FREE: 5作品まで作成可能", "プラン制限", "FREEプラン/4作品作成済み",
     "1. /api/artworks にPOST\n2. title: 「5個目の作品」を入力\n3. imageUrl: 「https://example.com/5.jpg」を入力",
     "status: 201, 成功", "Phase1", "", "", ""],
    ["ART-017", "作品", "プラン制限", "FREE: 6作品目で制限", "プラン制限", "FREEプラン/5作品作成済み",
     "1. /api/artworks にPOST\n2. title: 「6個目の作品」を入力\n3. imageUrl: 「https://example.com/6.jpg」を入力",
     "status: 403, LIMIT_EXCEEDED", "Phase1", "", "", ""],
    ["ART-018", "作品", "プラン制限", "PRO: 50作品まで", "プラン制限", "PROプラン",
     "1. /api/artworks にPOST\n2. 50個目以上の作品作成を試行",
     "status: 201, 成功（50作品目まで）", "Phase1", "", "", ""],

    # SNSリンクテスト
    ["SOCIAL-001", "SNSリンク", "一覧取得", "SNSリンク一覧取得", "正常系", "ログイン済み",
     "1. /api/social-links にGET",
     "status: 200, リンク一覧", "Phase1", "", "", ""],
    ["SOCIAL-002", "SNSリンク", "作成", "新規SNSリンク作成", "正常系", "ログイン済み",
     "1. /api/social-links にPOST\n2. platform: 「Twitter」を入力\n3. url: 「https://twitter.com/testuser」を入力",
     "status: 201, 作成されたリンク", "Phase1", "", "", ""],
    ["SOCIAL-003", "SNSリンク", "作成", "URL無しで作成", "異常系", "ログイン済み",
     "1. /api/social-links にPOST\n2. platform: 「Twitter」を入力\n3. url: 「」（空）",
     "status: 400, urlは必須", "Phase1", "", "", ""],
    ["SOCIAL-004", "SNSリンク", "作成", "無効なURL形式", "異常系", "ログイン済み",
     "1. /api/social-links にPOST\n2. platform: 「Twitter」を入力\n3. url: 「invalid-url」を入力",
     "status: 400, URL形式エラー", "Phase1", "", "", ""],
    ["SOCIAL-005", "SNSリンク", "更新", "SNSリンク更新", "正常系", "ログイン済み/リンクあり",
     "1. /api/social-links/{id} にPUT\n2. id: 「1」を指定\n3. url: 「https://twitter.com/newuser」を入力",
     "status: 200", "Phase1", "", "", ""],
    ["SOCIAL-006", "SNSリンク", "削除", "SNSリンク削除", "正常系", "ログイン済み/リンクあり",
     "1. /api/social-links/{id} にDELETE\n2. id: 「1」を指定",
     "status: 200 or 204", "Phase1", "", "", ""],
    ["SOCIAL-007", "SNSリンク", "並び替え", "SNSリンク並び替え", "正常系", "複数リンクあり",
     "1. /api/social-links/reorder にPUT\n2. orderedIds: 「[2, 1]」を入力",
     "status: 200", "Phase1", "", "", ""],
    ["SOCIAL-008", "SNSリンク", "プラン制限", "FREE: 2リンクまで", "プラン制限", "FREEプラン/1リンクあり",
     "1. /api/social-links にPOST\n2. platform: 「Instagram」を入力\n3. url: 「https://instagram.com/test」を入力",
     "status: 201, 成功", "Phase1", "", "", ""],
    ["SOCIAL-009", "SNSリンク", "プラン制限", "FREE: 3リンク目で制限", "プラン制限", "FREEプラン/2リンクあり",
     "1. /api/social-links にPOST\n2. platform: 「YouTube」を入力\n3. url: 「https://youtube.com/@test」を入力",
     "status: 403, LIMIT_EXCEEDED", "Phase1", "", "", ""],

    # 公開ページテスト
    ["PUBLIC-001", "公開ページ", "取得", "公開ページ表示", "正常系", "公開プロフィールあり",
     "1. /api/public/{username} にGET\n2. username: 「test_user」を指定",
     "status: 200, 公開情報", "Phase1", "", "", ""],
    ["PUBLIC-002", "公開ページ", "取得", "存在しないユーザー", "異常系", "なし",
     "1. /api/public/{username} にGET\n2. username: 「nonexistent_user」を指定",
     "status: 404, USER_NOT_FOUND", "Phase1", "", "", ""],
    ["PUBLIC-003", "公開ページ", "取得", "作品一覧含む", "正常系", "公開作品あり",
     "1. /api/public/{username} にGET\n2. username: 「test_user」を指定",
     "artworks配列に作品含む", "Phase1", "", "", ""],
    ["PUBLIC-004", "公開ページ", "取得", "SNSリンク含む", "正常系", "公開リンクあり",
     "1. /api/public/{username} にGET\n2. username: 「test_user」を指定",
     "socialLinks配列にリンク含む", "Phase1", "", "", ""],

    # 投稿テスト (Phase2)
    ["POST-001", "投稿", "一覧取得", "投稿一覧取得", "正常系", "ログイン済み",
     "1. /api/posts にGET",
     "status: 200, 投稿一覧", "Phase2", "", "", ""],
    ["POST-002", "投稿", "作成", "新規投稿作成", "正常系", "ログイン済み",
     "1. /api/posts にPOST\n2. title: 「テスト投稿」を入力\n3. content: 「投稿の内容です。」を入力",
     "status: 201, 作成された投稿", "Phase2", "", "", ""],
    ["POST-003", "投稿", "作成", "タイトルなしで作成", "異常系", "ログイン済み",
     "1. /api/posts にPOST\n2. title: 「」（空）\n3. content: 「内容」を入力",
     "status: 400, titleは必須", "Phase2", "", "", ""],
    ["POST-004", "投稿", "作成", "コンテンツなしで作成", "異常系", "ログイン済み",
     "1. /api/posts にPOST\n2. title: 「タイトル」を入力\n3. content: 「」（空）",
     "status: 400, contentは必須", "Phase2", "", "", ""],
    ["POST-005", "投稿", "作成", "最大タイトル長", "境界値", "ログイン済み",
     "1. /api/posts にPOST\n2. title: 「あ」×200（200文字）を入力\n3. content: 「内容」を入力",
     "status: 201, 成功", "Phase2", "", "", ""],
    ["POST-006", "投稿", "作成", "タイトル超過", "境界値", "ログイン済み",
     "1. /api/posts にPOST\n2. title: 「あ」×201（201文字）を入力",
     "status: 400, 200文字以内", "Phase2", "", "", ""],
    ["POST-007", "投稿", "更新", "投稿更新", "正常系", "ログイン済み/投稿あり",
     "1. /api/posts/{id} にPUT\n2. id: 「1」を指定\n3. title: 「更新後タイトル」を入力",
     "status: 200", "Phase2", "", "", ""],
    ["POST-008", "投稿", "削除", "投稿削除", "正常系", "ログイン済み/投稿あり",
     "1. /api/posts/{id} にDELETE\n2. id: 「1」を指定",
     "status: 200 or 204", "Phase2", "", "", ""],
    ["POST-009", "投稿", "公開", "投稿の公開設定", "正常系", "ログイン済み",
     "1. /api/posts/{id} にPUT\n2. id: 「1」を指定\n3. published: 「true」を入力",
     "status: 200, 公開状態", "Phase2", "", "", ""],
    ["POST-010", "投稿", "プラン制限", "FREE: 1投稿まで", "プラン制限", "FREEプラン/0投稿",
     "1. /api/posts にPOST\n2. title: 「1個目の投稿」を入力\n3. content: 「内容」を入力",
     "status: 201, 成功", "Phase2", "", "", ""],
    ["POST-011", "投稿", "プラン制限", "FREE: 2投稿目で制限", "プラン制限", "FREEプラン/1投稿あり",
     "1. /api/posts にPOST\n2. title: 「2個目の投稿」を入力\n3. content: 「内容」を入力",
     "status: 403, LIMIT_EXCEEDED", "Phase2", "", "", ""],

    # テーマテスト (Phase2)
    ["THEME-001", "テーマ", "取得", "テーマ設定取得", "正常系", "ログイン済み",
     "1. /api/profile/theme にGET",
     "status: 200, テーマ設定", "Phase2", "", "", ""],
    ["THEME-002", "テーマ", "更新", "primaryColor更新", "正常系", "ログイン済み",
     "1. /api/profile にPUT\n2. primaryColor: 「#FF0000」を入力",
     "status: 200, 色更新", "Phase2", "", "", ""],
    ["THEME-003", "テーマ", "更新", "backgroundColor更新", "正常系", "ログイン済み",
     "1. /api/profile にPUT\n2. backgroundColor: 「#000000」を入力",
     "status: 200", "Phase2", "", "", ""],
    ["THEME-004", "テーマ", "更新", "無効なカラーコード", "異常系", "ログイン済み",
     "1. /api/profile にPUT\n2. primaryColor: 「invalid」を入力",
     "status: 400, 無効な色形式", "Phase2", "", "", ""],
    ["THEME-005", "テーマ", "更新", "layoutType更新", "正常系", "ログイン済み",
     "1. /api/profile にPUT\n2. layoutType: 「GRID」を入力",
     "status: 200", "Phase2", "", "", ""],
    ["THEME-006", "テーマ", "プラン制限", "FREE: 基本テーマのみ", "プラン制限", "FREEプラン",
     "1. /api/profile にPUT\n2. primaryColor: 「#FF0000」を入力",
     "status: 403 or 200 (制限あり)", "Phase2", "", "", ""],
    ["THEME-007", "テーマ", "プラン制限", "PRO: 全テーマ利用可能", "プラン制限", "PROプラン",
     "1. /api/profile にPUT\n2. primaryColor: 「#FF0000」を入力\n3. fontFamily: 「serif」を入力",
     "status: 200", "Phase2", "", "", ""],

    # カテゴリテスト (Phase2)
    ["CAT-001", "カテゴリ", "一覧取得", "カテゴリ一覧取得", "正常系", "ログイン済み（PRO以上）",
     "1. /api/categories にGET",
     "status: 200, カテゴリ一覧", "Phase2", "", "", ""],
    ["CAT-002", "カテゴリ", "作成", "新規カテゴリ作成", "正常系", "ログイン済み（PRO以上）",
     "1. /api/categories にPOST\n2. name: 「イラスト」を入力",
     "status: 201, 作成されたカテゴリ", "Phase2", "", "", ""],
    ["CAT-003", "カテゴリ", "作成", "名前なしで作成", "異常系", "ログイン済み",
     "1. /api/categories にPOST\n2. name: 「」（空）",
     "status: 400, nameは必須", "Phase2", "", "", ""],
    ["CAT-004", "カテゴリ", "作成", "重複名で作成", "異常系", "同名カテゴリ「イラスト」あり",
     "1. /api/categories にPOST\n2. name: 「イラスト」を入力",
     "status: 409 or 400, 重複エラー", "Phase2", "", "", ""],
    ["CAT-005", "カテゴリ", "作成", "最大名前長", "境界値", "ログイン済み（PRO以上）",
     "1. /api/categories にPOST\n2. name: 「あ」×50（50文字）を入力",
     "status: 201, 成功", "Phase2", "", "", ""],
    ["CAT-006", "カテゴリ", "作成", "名前超過", "境界値", "ログイン済み",
     "1. /api/categories にPOST\n2. name: 「あ」×51（51文字）を入力",
     "status: 400, 50文字以内", "Phase2", "", "", ""],
    ["CAT-007", "カテゴリ", "更新", "カテゴリ更新", "正常系", "カテゴリあり",
     "1. /api/categories/{id} にPUT\n2. id: 「1」を指定\n3. name: 「マンガ」を入力",
     "status: 200", "Phase2", "", "", ""],
    ["CAT-008", "カテゴリ", "削除", "カテゴリ削除", "正常系", "カテゴリあり（使用中でない）",
     "1. /api/categories/{id} にDELETE\n2. id: 「1」を指定",
     "status: 200 or 204", "Phase2", "", "", ""],
    ["CAT-009", "カテゴリ", "並び替え", "カテゴリ並び替え", "正常系", "複数カテゴリあり",
     "1. /api/categories/reorder にPUT\n2. orderedIds: 「[2, 1, 3]」を入力",
     "status: 200", "Phase2", "", "", ""],
    ["CAT-010", "カテゴリ", "プラン制限", "FREE: カテゴリ使用不可", "プラン制限", "FREEプラン",
     "1. /api/categories にPOST\n2. name: 「テスト」を入力",
     "status: 403, PLAN_REQUIRED", "Phase2", "", "", ""],

    # タグテスト (Phase2)
    ["TAG-001", "タグ", "一覧取得", "タグ一覧取得", "正常系", "ログイン済み（PRO以上）",
     "1. /api/tags にGET",
     "status: 200, タグ一覧", "Phase2", "", "", ""],
    ["TAG-002", "タグ", "作成", "新規タグ作成", "正常系", "ログイン済み（PRO以上）",
     "1. /api/tags にPOST\n2. name: 「オリジナル」を入力",
     "status: 201, 作成されたタグ", "Phase2", "", "", ""],
    ["TAG-003", "タグ", "作成", "名前なしで作成", "異常系", "ログイン済み",
     "1. /api/tags にPOST\n2. name: 「」（空）",
     "status: 400, nameは必須", "Phase2", "", "", ""],
    ["TAG-004", "タグ", "作成", "最大名前長", "境界値", "ログイン済み（PRO以上）",
     "1. /api/tags にPOST\n2. name: 「あ」×30（30文字）を入力",
     "status: 201, 成功", "Phase2", "", "", ""],
    ["TAG-005", "タグ", "作成", "名前超過", "境界値", "ログイン済み",
     "1. /api/tags にPOST\n2. name: 「あ」×31（31文字）を入力",
     "status: 400, 30文字以内", "Phase2", "", "", ""],
    ["TAG-006", "タグ", "更新", "タグ更新", "正常系", "タグあり",
     "1. /api/tags/{id} にPUT\n2. id: 「1」を指定\n3. name: 「ファンアート」を入力",
     "status: 200", "Phase2", "", "", ""],
    ["TAG-007", "タグ", "削除", "タグ削除", "正常系", "タグあり（使用中でない）",
     "1. /api/tags/{id} にDELETE\n2. id: 「1」を指定",
     "status: 200 or 204", "Phase2", "", "", ""],
    ["TAG-008", "タグ", "作品紐付け", "作品にタグ紐付け", "正常系", "作品/タグあり",
     "1. /api/artworks/{id} にPUT\n2. id: 「1」を指定\n3. tagIds: 「[1, 2]」を入力",
     "status: 200, タグ紐付け", "Phase2", "", "", ""],
    ["TAG-009", "タグ", "プラン制限", "FREE: タグ使用不可", "プラン制限", "FREEプラン",
     "1. /api/tags にPOST\n2. name: 「テスト」を入力",
     "status: 403, PLAN_REQUIRED", "Phase2", "", "", ""],

    # 作品カテゴリ紐付け (Phase2)
    ["ART-CAT-001", "作品カテゴリ", "紐付け", "作品にカテゴリ紐付け", "正常系", "作品/カテゴリあり",
     "1. /api/artworks/{id} にPUT\n2. id: 「1」を指定\n3. categoryId: 「1」を入力",
     "status: 200, カテゴリ紐付け", "Phase2", "", "", ""],
    ["ART-CAT-002", "作品カテゴリ", "解除", "作品のカテゴリ解除", "正常系", "紐付けあり",
     "1. /api/artworks/{id} にPUT\n2. id: 「1」を指定\n3. categoryId: 「null」を入力",
     "status: 200, 紐付け解除", "Phase2", "", "", ""],

    # 公開ページフィルタ (Phase2)
    ["PUBLIC-CAT-001", "公開ページカテゴリ", "フィルタ", "カテゴリでフィルタ", "正常系", "カテゴリ紐付けあり",
     "1. /api/public/{username}?categoryId={id} にGET\n2. username: 「test_user」を指定\n3. categoryId: 「1」を指定",
     "フィルタされた作品", "Phase2", "", "", ""],
    ["PUBLIC-TAG-001", "公開ページタグ", "フィルタ", "タグでフィルタ", "正常系", "タグ紐付けあり",
     "1. /api/public/{username}?tagId={id} にGET\n2. username: 「test_user」を指定\n3. tagId: 「1」を指定",
     "フィルタされた作品", "Phase2", "", "", ""],
    ["PUBLIC-POST-001", "公開ページ投稿", "取得", "公開投稿一覧", "正常系", "公開投稿あり",
     "1. /api/public/{username} にGET\n2. username: 「test_user」を指定",
     "posts配列に投稿含む", "Phase2", "", "", ""],
    ["PUBLIC-POST-002", "公開ページ投稿", "取得", "非公開投稿除外", "正常系", "非公開投稿あり",
     "1. /api/public/{username} にGET\n2. username: 「test_user」を指定",
     "非公開投稿は含まない", "Phase2", "", "", ""],

    # UIテスト
    ["DASH-001", "ダッシュボード", "表示", "ダッシュボード表示", "正常系", "ログイン済み",
     "1. ブラウザで /dashboard にアクセス",
     "統計情報表示", "Phase1", "", "", ""],
    ["DASH-002", "ダッシュボード", "表示", "未認証リダイレクト", "異常系", "未ログイン",
     "1. ブラウザで /dashboard にアクセス（未ログイン状態）",
     "/login にリダイレクト", "Phase1", "", "", ""],
    ["UI-001", "UI", "ログインフォーム", "ログイン画面表示", "正常系", "なし",
     "1. ブラウザで /login にアクセス",
     "ログインフォーム表示", "Phase1", "", "", ""],
    ["UI-002", "UI", "サインアップフォーム", "サインアップ画面表示", "正常系", "なし",
     "1. ブラウザで /signup にアクセス",
     "サインアップフォーム表示", "Phase1", "", "", ""],
    ["UI-003", "UI", "サイドバー", "サイドバーナビゲーション", "正常系", "ログイン済み",
     "1. ダッシュボードでサイドバー確認\n2. 各メニュー項目をクリック",
     "全メニュー項目表示", "Phase1", "", "", ""],
    ["UI-004", "UI", "レスポンシブ", "モバイル表示", "正常系", "なし",
     "1. ブラウザの開発者ツールでモバイルサイズ（375px）に変更\n2. 各画面を確認",
     "レスポンシブ対応", "Phase1", "", "", ""],
    ["UI-005", "UI", "公開ページ", "公開ページ表示", "正常系", "公開プロフィールあり",
     "1. ブラウザで /{username} にアクセス\n2. username: 「test_user」を指定",
     "公開ページ正常表示", "Phase1", "", "", ""],
]

# データ書き込み
for row_num, row_data in enumerate(test_cases, 2):
    for col_num, value in enumerate(row_data, 1):
        cell = ws.cell(row=row_num, column=col_num, value=value)
        cell.alignment = Alignment(vertical='top', wrap_text=True)
        cell.border = thin_border

# 列幅調整
column_widths = [12, 12, 12, 25, 10, 25, 50, 30, 10, 12, 12, 20]
for col_num, width in enumerate(column_widths, 1):
    ws.column_dimensions[get_column_letter(col_num)].width = width

# 行高さ調整
for row in range(2, len(test_cases) + 2):
    ws.row_dimensions[row].height = 60

# テスト結果列の条件付き書式用コメント追加
ws.cell(row=1, column=10).comment = None  # openpyxlでは条件付き書式がサポートされないためスキップ

# 保存
output_path = '/mnt/c/OsakanaFactory/workspace/PicMe/docs/test/PicMe_テスト仕様書_v2.1.xlsx'
wb.save(output_path)
print(f"Saved to: {output_path}")
